print(ord("A"))
print(ord("a"))
print(ord("Ą"))
print(ord("ą"))
print("Abc" < "Abd")
print("Abc" <= "Abd")
print("Abc" == "Abd")
print("Abc" == "Abc")
print("Abc" > "Abd")
lista = [3, 4, 8.7, -3, -11, 9.0]
lista.sort()
print(lista)